<a href="https://colab.research.google.com/github/lesya-git-hub/29_03_2026/blob/main/dt_sc_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
np.__version__

'2.0.2'

In [4]:
a = np.random.randint(1,6,(3,3))
a

array([[5, 3, 5],
       [4, 2, 1],
       [3, 3, 4]])

In [5]:
np.linalg.det(a)

np.float64(15.999999999999991)

In [6]:
np.prod(a)

np.int64(21600)

In [7]:
np.prod(a[0])

np.int64(75)

In [8]:
np.prod(a[1])

np.int64(8)

In [9]:
np.prod(a[2])

np.int64(36)

In [10]:
np.sum(a)

np.int64(30)

In [11]:
np.max(a)

np.int64(5)

In [12]:
np.min(a)

np.int64(1)

In [13]:
np.mean(a)

np.float64(3.3333333333333335)

In [14]:
np.sqrt(a)

array([[2.23606798, 1.73205081, 2.23606798],
       [2.        , 1.41421356, 1.        ],
       [1.73205081, 1.73205081, 2.        ]])

In [16]:
np.sum(a, axis= 1).reshape(-1,1)

array([[13],
       [ 7],
       [10]])

In [18]:
vector = np.random.randint(0,10,size = 25)
vector

array([8, 3, 1, 8, 5, 9, 9, 4, 4, 4, 4, 0, 0, 7, 6, 5, 5, 2, 8, 7, 8, 8,
       9, 6, 8])

In [19]:
np.sort(vector)[::-1]

array([9, 9, 9, 8, 8, 8, 8, 8, 8, 7, 7, 6, 6, 5, 5, 5, 4, 4, 4, 4, 3, 2,
       1, 0, 0])

In [20]:
np.median(vector)

np.float64(6.0)

In [21]:
np.mean(vector)

np.float64(5.52)

In [22]:
np.max(vector)

np.int64(9)

In [23]:
np.min(vector)

np.int64(0)

In [24]:
from scipy import stats

In [25]:
stats.mode(vector)

ModeResult(mode=np.int64(8), count=np.int64(6))

In [26]:
m1 = np.random.randint(1,11, size=(4,4))
m1

array([[ 7,  1, 10,  7],
       [ 4,  2,  2, 10],
       [ 3,  9,  2,  7],
       [ 8,  1,  5,  9]])

In [27]:
m2 = np.random.randint(1,11, size=(4,4))
m2

array([[ 5,  3, 10,  5],
       [10,  8, 10,  1],
       [ 1,  3,  2,  3],
       [ 4,  7,  8,  2]])

In [28]:
m1+m2

array([[12,  4, 20, 12],
       [14, 10, 12, 11],
       [ 4, 12,  4, 10],
       [12,  8, 13, 11]])

In [29]:
m1*m2

array([[ 35,   3, 100,  35],
       [ 40,  16,  20,  10],
       [  3,  27,   4,  21],
       [ 32,   7,  40,  18]])

In [30]:
m1-m2

array([[ 2, -2,  0,  2],
       [-6, -6, -8,  9],
       [ 2,  6,  0,  4],
       [ 4, -6, -3,  7]])

In [31]:
m1/m2

array([[ 1.4       ,  0.33333333,  1.        ,  1.4       ],
       [ 0.4       ,  0.25      ,  0.2       , 10.        ],
       [ 3.        ,  3.        ,  1.        ,  2.33333333],
       [ 2.        ,  0.14285714,  0.625     ,  4.5       ]])

In [32]:
np.dot(m1,m2)

array([[ 83, 108, 156,  80],
       [ 82, 104, 144,  48],
       [135, 136, 180,  44],
       [ 91, 110, 172,  74]])

In [36]:
v1 = np.arange(9.0)
v1

array([0., 1., 2., 3., 4., 5., 6., 7., 8.])

In [37]:
v2 = v1.reshape(3,3)
v2

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [39]:
v3 = np.arange(3.0)
v3

array([0., 1., 2.])

In [40]:
np.multiply(v2,v3)

array([[ 0.,  1.,  4.],
       [ 0.,  4., 10.],
       [ 0.,  7., 16.]])

In [41]:
x1 = np.arange(6)
x1

array([0, 1, 2, 3, 4, 5])

In [42]:
np.power(x1, 3)

array([  0,   1,   8,  27,  64, 125])

In [45]:
x2 = np.array([1,2,3,4,5])
x2

array([1, 2, 3, 4, 5])

In [47]:
x3 = np.arange(5)
x3

array([0, 1, 2, 3, 4])

In [48]:
x2**x3

array([  1,   2,   9,  64, 625])

In [49]:
x2**3

array([  1,   8,  27,  64, 125])