<a href="https://colab.research.google.com/github/lesya-git-hub/29_03_2026/blob/main/dt_sc_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
np.__version__

'2.0.2'

In [3]:
v = np.array([1,2])
v

array([1, 2])

In [5]:
v = np.array([1,2,3,4,5], dtype = float)
v

array([1., 2., 3., 4., 5.])

In [6]:
v [0]

np.float64(1.0)

In [7]:
v[-1]

np.float64(5.0)

In [9]:
a = np.array([[1,2,3],[-2,3,4],[1,-2,3]])
a

array([[ 1,  2,  3],
       [-2,  3,  4],
       [ 1, -2,  3]])

In [10]:
a[0,0]

np.int64(1)

In [12]:
a.dtype

dtype('int64')

In [13]:
a.shape

(3, 3)

In [14]:
a.size

9

In [15]:
b = np.matrix([[-2,1,3],[3,-1,4],[3,1,7]])
b

matrix([[-2,  1,  3],
        [ 3, -1,  4],
        [ 3,  1,  7]])

In [16]:
a_diag = np.diag(a)
a_diag

array([1, 3, 3])

In [18]:
diag_m=np.diag(a_diag)
diag_m

array([[1, 0, 0],
       [0, 3, 0],
       [0, 0, 3]])

In [19]:
np.zeros((3,3), dtype = int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [20]:
np.random.randint(11,size=(4,4))

array([[ 4,  9,  2,  7],
       [ 8,  4,  3,  0],
       [ 7, 10,  3,  0],
       [ 9,  4,  3,  0]])

In [21]:
np.ones(2)

array([1., 1.])

In [23]:
c = np.array([[1,2,4],[3,2,7],[-4,2,8]], dtype=float)
c

array([[ 1.,  2.,  4.],
       [ 3.,  2.,  7.],
       [-4.,  2.,  8.]])

In [25]:
np.arange(2,9,2)

array([2, 4, 6, 8])

In [27]:
np.linspace(0,10)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [28]:
np.ones((3,3), dtype = int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [29]:
a.T

array([[ 1, -2,  1],
       [ 2,  3, -2],
       [ 3,  4,  3]])

In [31]:
a.transpose()

array([[ 1, -2,  1],
       [ 2,  3, -2],
       [ 3,  4,  3]])

In [32]:
a

array([[ 1,  2,  3],
       [-2,  3,  4],
       [ 1, -2,  3]])

In [34]:
np.linalg.det(a)

np.float64(40.000000000000014)

In [35]:
np.linalg.det(b)

np.float64(31.0)

In [36]:
3*a

array([[ 3,  6,  9],
       [-6,  9, 12],
       [ 3, -6,  9]])

In [37]:
a+b

matrix([[-1,  3,  6],
        [ 1,  2,  8],
        [ 4, -1, 10]])

In [38]:
a

array([[ 1,  2,  3],
       [-2,  3,  4],
       [ 1, -2,  3]])

In [39]:
b

matrix([[-2,  1,  3],
        [ 3, -1,  4],
        [ 3,  1,  7]])

In [40]:
a-b

matrix([[ 3,  1,  0],
        [-5,  4,  0],
        [-2, -3, -4]])

In [41]:
a*b

matrix([[13,  2, 32],
        [25, -1, 34],
        [ 1,  6, 16]])

In [42]:
np.dot(a,b)

matrix([[13,  2, 32],
        [25, -1, 34],
        [ 1,  6, 16]])

In [43]:
a

array([[ 1,  2,  3],
       [-2,  3,  4],
       [ 1, -2,  3]])

In [45]:
np.linalg.inv(a)

array([[ 4.25000000e-01, -3.00000000e-01, -2.50000000e-02],
       [ 2.50000000e-01,  1.58603289e-17, -2.50000000e-01],
       [ 2.50000000e-02,  1.00000000e-01,  1.75000000e-01]])